// 쿠폰 데이터
const coupons = [
  { code: "RINKARMA", desc: "4성 전설 영웅 '린'" },
  { code: "SECRETCODE", desc: "루비 300개, 열쇠 30개" },
  { code: "777SENARE", desc: "루비 300개, 열쇠 30개" },
  { code: "JJOLJACK", desc: "루비 300개, 열쇠 30개" },
  { code: "LOVESENA", desc: "루비 300개, 열쇠 30개" },
  { code: "SENAREGOGO", desc: "골드 30만" },
  { code: "SENA7SENA", desc: "" },
  { code: "GOODLUCK", desc: "골드 30만" },
  { code: "SEVENVSDARK", desc: "골드 30만" },
  { code: "7777777", desc: "골드 30만" },
  { code: "MAYSLETTER", desc: "" },
  { code: "SURPRISE", desc: "골드 30만" },
  { code: "THEMONTHOFSENA", desc: "골드 30만" },
  { code: "LETSDOSNEA", desc: "" },
  { code: "7SENASENA7", desc: "이벤트 펫 [희귀] 두" },
  { code: "INTOTHESENA", desc: "열쇠 상자 5개" },
  { code: "HOTCOSTUME", desc: "" },
  { code: "REBIRTHBACK", desc: "열쇠 상자 5개" },
  { code: "WELCOMEBACK", desc: "열쇠 상자 5개" },
  { code: "GACHAGETCHA", desc: "" },
  { code: "BLINGBLING", desc: "열쇠 상자 3개, 골드 10만" },
  { code: "", desc: "" },
  { code: "LODING", desc: "열쇠 상자 3개, 골드 10만" },
  { code: "GUILDWAR", desc: "이벤트 펫 [희귀] 미믹" },
  { code: "HEROSOMMON", desc: "열쇠 240개, 골드 15만" },
  { code: "CHECKSTORAGE", desc: "" },
  { code: "INFOCODEX", desc: "열쇠 120개, 골드 15만" },
  { code: "RANKUPGOGO", desc: "" },
  { code: "SENAARENA", desc: "" },
  { code: "COMINGSOONPLATIN", desc: "" },
  { code: "CUTEECHO", desc: "" },
  { code: "POOKIHAPPY", desc: "" },
  { code: "BONVOYAGE", desc: "픽업 소환 이용권 5개" },
  { code: "DAILYMISSIONS", desc: "" },
  { code: "INFINITETOWER", desc: "영웅 소환 이용권 5개" },
  { code: "STORYEVENT", desc: "영웅 소환 이용권 5개" },
  { code: "EVANKARIN", desc: "영웅 소환 이용권 5개" },
  { code: "SENARAID", desc: "영웅 소환 이용권 5개" },
  { code: "WELCOMESENA", desc: "펫 소환 이용권 5개" },
  { code: "MOONLIGHTCOAST", desc: "펫 소환 이용권 5개" },
  { code: "MOREKEYS", desc: "푸키의 증표 2개, 열쇠 상자 1개" },
  { code: "SHOWMETHEMONEY", desc: "푸키의 증표 2개, 열쇠 상자 1개" },
  { code: "ILOVEPICKUP", desc: "" },
  { code: "MAILBOX", desc: "진화 재료 상자 (중) 50개" },
  { code: "BESTGUILD", desc: "" },
  { code: "RELEASEPET", desc: "진화재료 선택 상자 (상) 30개" },
  { code: "PEPEPOPO", desc: "" },
  { code: "NOHOSCHRONICLE", desc: "일반 영웅 소환권 10개" },
  { code: "UPDATES", desc: "일반 영웅 소환권 10개" },
  { code: "THANKYOU", desc: "일반 영웅 소환권 10개" },
  { code: "SENAHAJASENA", desc: "일반 영웅 소환권 10개" },
  { code: "PETEGG", desc: "" },
  { code: "ARENAGOLD", desc: "" },
  { code: "NOMARLHERO", desc: "" },
  { code: "FORTAGNIA", desc: "고급 영웅 소환권 10개" },
  { code: "YUISSONG", desc: "고급 영웅 소환권 10개" },
  { code: "YONGSANIM", desc: "고급 영웅 소환권 10개" },
  { code: "PUKIDANCE", desc: "고급 영웅 소환권 10개" },
  { code: "ADVENTURER", desc: "고급 영웅 소환권 10개" },
  { code: "PROFILE", desc: "" },
  { code: "SKYGATE", desc: "" },
  { code: "LEGENDSRAID", desc: "희귀 영웅 소환권 1개, 골드 10만" },
  { code: "SHININGPRISM", desc: "희귀 영웅 소환권 1개, 골드 10만" },
  { code: "POWERUPHERO", desc: "" },
  { code: "HTRIBERANES", desc: "희귀 영웅 소환권 1개, 골드 10만" },
  { code: "SADENDING", desc: "희귀~전설 영웅 소환권 1개" },
  { code: "TREASURE", desc: "6성 희귀 영웅 소환권 1개" },
  { code: "THEHOLYCROSS", desc: "6성 희귀 영웅 소환권 1개" },
  { code: "VALKYRIE", desc: "일반 스킬 강화석 1개" },
  { code: "LOVELYRUBY", desc: "일반 스킬 강화석 1개" },
  { code: "DEVELOPERNOTES", desc: "" },
  { code: "SENAEVENTS", desc: "일반 스킬 강화석 1개" },
  { code: "CMMAY", desc: "고급 알 2개, 중급 알 2개, 하급 알 3개" },
  { code: "PDKIMJUNGKI", desc: "고급 알 2개, 중급 알 2개, 하급 알 3개" },
  { code: "FUSEGETSPECIAL", desc: "고급 알 2개, 중급 알 2개, 하급 알 3개" },
  { code: "DARKKNIGHTS", desc: "고급 알 2개, 중급 알 2개, 하급 알 3개" },
  { code: "JULYSENAMONTH", desc: "고급 알 2개, 중급 알 2개, 하급 알 3개" },
];
